// Generated by scripts/build-world-data.mjs during production builds.
// The checked-in placeholder keeps offline development available; empty packed
// fields fall back to the analytic environment provider.
const emptyGrid = {
  minLat: 0,
  maxLat: 0,
  minLon: 0,
  maxLon: 0,
  stepDeg: 1,
  latCount: 1,
  lonCount: 1,
  months: 12,
  components: 2,
  scale: 100,
  missing: -32768,
  packed: '',
} as const;

export const ATLANTIC_CLIMATOLOGY = {
  source: 'placeholder',
  generatedAt: '',
  wind: emptyGrid,
  current: emptyGrid,
} as const;
