// Generated by scripts/build-world-data.mjs during production builds.
// The checked-in placeholder keeps offline development available; when `packed`
// is empty, the environment layer falls back to the analytic climatology.
export const ATLANTIC_CLIMATOLOGY = {
  source: 'placeholder',
  generatedAt: '',
  minLat: -60,
  maxLat: 65,
  minLon: -100,
  maxLon: 30,
  stepDeg: 5,
  latCount: 26,
  lonCount: 27,
  months: 12,
  scale: 100,
  missing: -32768,
  packed: '',
} as const;
